### ISSUE TITLE
Is there a min number of tests for FDR methods?

### ISSUE THREAD

**Issue by stephaniehicks** [pkimes/benchmark-fdr#12]
- Is there a minimum number of tests for the methods to work?
- Getting warnings for fdrtool. 
- In IHW, defaults to one bin if you only have only 600 tests (e.g. microbiome data)

**Comment by ayshwaryas** [comment]
I did not check the number of tests in their simulations but all the real data applications in the IHW paper have at least 2666 tests. That probably explains why they provide the number of bins as input for the real data analyses.

**Comment by cduvallet** [comment]
From the [code](https://github.com/nignatiadis/IHW/blob/master/R/ihw_convex.R#L132), the number of bins is automatically determined as: 

`nbins <- max(1,min(40, floor(length(pvalues)/1500)))`.

So we'll need to input the number of bins manually for real data analyses which don't have that many tests.

**Comment by pkimes** [comment]
Closing this issue - feel free to reopen if it should be discussed.

It looks like the line in the IHW repo that Claire was referencing moved since the authors updated the  code. Tip for linking to code on GitHub: when browsing code, hit the "y" key on your keyboard. The URL will include the commit hash so you can link to the exact version of the code. (random knowledge passed on to me by someone a couple years ago.)

reference to that random bit of information:
https://help.github.com/articles/getting-permanent-links-to-files/

**Comment by cduvallet** [comment]
Amazing!!!

Looks like the same line is now [here](https://github.com/nignatiadis/IHW/blob/010dafc8baaac17bdf1eed8ee8fd6947c66eaa27/R/ihw_convex.R#L149)

And I agree this is good to be closed - we mention that IHW collapses to BH when there aren't enough tests in the manuscript, which addresses this point.
